name: Sync multiple branches
on:
  workflow_dispatch:

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
          - name: Run the Action
            uses: devops-infra/action-pull-request@v0.5.5
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              source_branch: staging
              target_branch: qa1
              title: My pull request
              body: "**Automated pull request**"
              draft: true
